### ISSUE TITLE
Playfab ios sdk issue 

### ISSUE THREAD

**Issue by devARL** [PlayFab/Objective_C_SDK#18]
A few hours ago , you commit latest change to your sdk, and i pull those changes and since then not able to build the code as your code is having issue in the SDK,

File: - PlayFabMultiplayerDataModels.m 
Line # : - 2246
error :- Implicit conversion of 'MultiplayerAzureRegion' to 'id _Nonnull' is disallowed with ARC
![Screen Shot 2019-04-25 at 10 54 01 AM 2](https://user-images.githubusercontent.com/36138362/56717584-6cb28d00-6756-11e9-8bd0-98ae4b602928.png)

**Comment by toddbellMSFT** [comment]
This was fixed back in June: https://github.com/PlayFab/SDKGenerator/commit/9b259df977ead45a98e971916f9dde99a04c05e1
